### ISSUE TITLE
CI tests fail to find and run consul executable

### ISSUE THREAD

**Issue by ketzacoatl** [alphaHeavy/consul-haskell#50]
See here for example - https://github.com/alphaHeavy/consul-haskell/pull/49/checks?check_run_id=2287576964:

![consul-haskell-ci-failure](https://user-images.githubusercontent.com/10122937/113877750-e95a9c80-97b0-11eb-8385-f61915eb27c2.png)

So the CI runner is unable to locate the `consul` executable.

All jobs are failing with this error.

**Comment by ketzacoatl** [comment]
Installing `consul`:

```
Run sudo make install-consul VERSION=1.10.0-alpha
if [ "1.10.0-alpha" = "" ]; then \
	echo "ERROR: Environment variable not set: \"VERSION\""; \
	exit 1; \
fi
wget -q 'https://releases.hashicorp.com/consul/1.10.0-alpha/consul_1.10.0-alpha_linux_amd64.zip'
unzip consul_1.10.0-alpha_linux_amd64.zip
Archive:  consul_1.10.0-alpha_linux_amd64.zip
  inflating: consul                  
mkdir -p ~/.local/bin/
mv consul ~/.local/bin/consul-1.10.0-alpha
chmod +x ~/.local/bin/consul-1.10.0-alpha
echo "installed consul to ~/.local/bin/consul-1.10.0-alpha"
installed consul to ~/.local/bin/consul-1.10.0-alpha
if [ "1.10.0-alpha" = "" ]; then \
	echo "ERROR: Environment variable not set: \"VERSION\""; \
	exit 1; \
fi
sudo ln -sf  ~/.local/bin/consul-1.10.0-alpha  ~/.local/bin/consul
```

* we have installed the executable to `~/.local/bin/consul-${VERSION}`
* we then link to that from `~/.local/bin/consul`
* and we then (later) need to be sure we define `PATH` and add our `~/.local/bin` to that path, which we do: `PATH=~/.local/bin/:$PATH`

**Comment by ketzacoatl** [comment]
Another weird bit about this, build succeeds, but tests fail, and their `PATH` is setup the same:
```
    - name: Build
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        PATH=~/.local/bin/:$PATH stack build --system-ghc ...

    - name: Test
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        PATH=~/.local/bin/:$PATH stack test --system-ghc ...
```
